# ================================================
# Sfixx x OSINT - Configuration
# ================================================
VERSION="1.5.0"
REPO_URL="https://github.com/shofakshafek/Sfixx-X-Osint.git"

# Timeout request (detik) untuk curl / API
TIMEOUT=10
